/**
 * What an experience is given, and what a venue assembles a hub from.
 *
 * The public surface of this package, and deliberately small: a base room that
 * has already dealt with who may be here, the shape of presence, and one
 * definition of what a StreetMesh hub is. An experience writes rules and
 * nothing else.
 *
 * There is no program in here any more. A hub is generated by the venue that
 * runs it, because only a venue knows what it has installed — this package is
 * the library that generated thing is built out of.
 */

export { VenueRoom, type JoinOptions, type Seated } from './room.ts'
export { Occupant, Occupancy, type OccupantType, type OccupancyType } from './presence.ts'
export { verifyTicket, type Ticket } from './ticket.ts'
export { hub, type HubOptions } from './hub.ts'
export { install, typeNameFor, type Experience, type RoomClass } from './install.ts'
export { routes, remember, forget } from './answers.ts'
