/**
 * This server's hub.
 *
 * Generated by `php artisan hub:build` from the experiences installed on
 * the venue that runs it. Nobody edits this file; edit the server.
 *
 * The transport is deliberately not named. Colyseus picks one, which is
 * what we want today, and WebTransport later is this file and nothing
 * else — which is the reason the hub stopped standing up a server of its
 * own.
 *
 * `@colyseus/tools` exports its `config()` as a CommonJS default, which
 * a type checker reading this as an ES module cannot call. It only
 * validates the options and hands them back, and `listen` takes them
 * either way — so the options are exported directly rather than
 * carrying a build failure for a function that does nothing here.
 */

import { hub } from './hub/mod.ts'
import experience0 from './rooms/com.streetmesh.games.chess/room.ts'

export default hub([
  experience0,
])
