/**
 * This server's hub.
 *
 * Generated by `php artisan hub:build` from the experiences installed on
 * the venue that runs it. Nobody edits this file; edit the server.
 *
 * The transport is deliberately not named. Colyseus picks one, which is
 * what we want today, and WebTransport later is this file and nothing
 * else — which is the reason the hub stopped standing up a server of its
 * own.
 */

import config from '@colyseus/tools'
import { hub } from './hub/mod.ts'
import experience0 from './rooms/com.streetmesh.games.chess/room.ts'

export default config(hub([
  experience0,
]))
