// Generated by `php artisan hub:build`. Nobody edits this file.
module.exports = {
  apps: [
    {
      name: 'streetmesh-hub',
      script: 'index.ts',
      interpreter: 'node',
      interpreter_args: '--experimental-strip-types',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        HUB_BUILD: '68f1a254cb405f04',
      },
    },
  ],
}
