// Generated by `php artisan hub:build`. Nobody edits this file.

import { readFileSync } from 'node:fs'
import { listen } from '@colyseus/tools'
import app from './app.config.ts'

/*
 * Which build this is, read from the artifact rather than the
 * environment. A process manager hands a process the environment it
 * started with, so a redeployed hub reported the build it replaced —
 * and a deploy waiting for the new one waited forever.
 */
process.env.HUB_BUILD = JSON.parse(
  readFileSync(new URL('./build.json', import.meta.url), 'utf8'),
).build

await listen(app)
